categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: ":raising_hand: Help wanted"
    label: "help wanted"
  - title: ":rotating_light: Testing"
    label: "testing"
  - title: ":hammer: Refactoring"
    label: "refactoring"
  - title: ":lipstick: Style"
    label: "style"
  - title: ":package: Dependencies"
    labels:
      - "dependencies"
      - "build"
template: |
  ## Changes

  $CHANGES