# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: Version Number
        required: true
        
permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ env.GITHUB_REF }}
        token: ${{ secrets.GH_TOKEN }}

    - name: Config Git Username
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9.x"
        
    - name: Install dependencies
      run: |
        pip install pdm
  
    - name: Build and Publish
      run: |
        pdm build

    # - name: Release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.event.inputs.version }}

    - name: Release
      uses: release-drafter/release-drafter@v5
      with:
        tag: v${{ github.event.inputs.version }}
        name: v${{ github.event.inputs.version }}
        version: v${{ github.event.inputs.version }}
        publish: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "dist-${{ github.event.inputs.version }}"
        path: |
          dist/*.tar.gz
          dist/*.whl

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        files: |
          dist/*.tar.gz
          dist/*.whl
